# Generated by Django 5.1.3 on 2024-11-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="fechaPublicado",
            field=models.DateField(default="2024-11-27"),
            preserve_default=False,
        ),
    ]
